### ISSUE TITLE
Question about Gamma correct and Texture format？

### ISSUE THREAD

**Issue by yanglebupt** [Twinklebear/webgpu-0-to-gltf#6]
Thank you very much for your tutorial！ It's really great！I just have a simple question.

In the `5-textures-ts` demo, `base_color_texture` is **sRGB space** format, so we need conduct gamma correct it to **linear space** in shader. After shader compute, we need to conduct inverse gamma correct to **sRGB space** for display.

But in tutorial，just conduct `linear_to_srgb`.  When read texture, no `srgb_to_linear` ?
 
![屏幕截图 2024-05-08 171116](https://github.com/Twinklebear/webgpu-0-to-gltf/assets/139488963/c61b63bf-8d9a-4021-88b3-182ef3cfd544)

And canvas format is `bgra8unorm` not **sRGB space** ?

![屏幕截图 2024-05-08 171634](https://github.com/Twinklebear/webgpu-0-to-gltf/assets/139488963/14d743ac-537e-4a67-b39d-4f1c0781476a)

So, I think the correct process is：

```typescript
let swapChainFormat = "bgra8unorm-srgb" as GPUTextureFormat;
  context.configure({
    device: device,
    format: swapChainFormat,
    usage: GPUTextureUsage.RENDER_ATTACHMENT,
  });
// fragment shader
@fragment
fn fragment_main(in: VertexOutput) -> @location(0) float4 {
    let base_color = textureSample(base_color_texture, base_color_sampler, in.texcoords);
    base_color = srgb_to_linear(base_color);

    var color = material_params.base_color_factor * base_color;
    
    color = linear_to_srgb(color);  // if canvas format is `srgb` else no need to do it
    color.w = 1.0;
    return color;
}
```
Do you think this process is correct？And I have another question, is `bgra8unorm` in **linear space**？Do I need gamma correct when read `bgra8unorm` format texture？

**Comment by Twinklebear** [comment]
Hi @yanglebupt , you're correct that we need to transform the sRGB colors to linear space for use in the shader, and then back to sRGB space for display. The current app code handles this correctly though:

- Sampling from the texture: To handle this in the app without requiring an `srgb_to_linear` call in the shader code I use an sRGB texture format for color textures: https://github.com/Twinklebear/webgpu-0-to-gltf/blob/main/5-textures-ts/src/gltf_texture.ts#L74-L86 . The sRGB color formats will perform the mapping from sRGB -> Linear for you when calling `textureSample` in the shader and return colors in linear space.
- Writing to the framebuffer: unfortunately the swap chain only supports `rgba8unorm` or `bgra8unorm` color formats: https://gpuweb.github.io/gpuweb/#dom-gpu-getpreferredcanvasformat , not sRGB. If we were using an sRGB render target (e.g., rendering to a texture) we could skip calling `linear_to_srgb`, but since the tutorial renders directly to the swap chain textures we need to do it in the shader in SW.

In summary, the texture formats:
- `rgba8unorm-srgb`: Texels are assumed to be in sRGB space, and when sampled in a shader the sRGB -> Linear conversion will be done for us and we get linear space values in the shader
- `rbga8unorm` and `bgra8unorm`: Texels are assumed to be in linear space and no conversion is done.

They key bit is that the color spaces are assumed, if you write/read sRGB colors to an `rgba8unorm` / `bgra8unorm` texture, you will write/read the same values with no conversion. So the end result is that the displayed colors will be in sRGB.

You can confirm this by changing to always use `rgba8unorm` texture here: https://github.com/Twinklebear/webgpu-0-to-gltf/blob/main/5-textures-ts/src/gltf_texture.ts#L74-L86 and do the conversion in software, you should find the image matches that produced by the current code.

**Comment by yanglebupt** [comment]
@Twinklebear  I understand what you mean. But when calculating PBR material, I still need `rgb2lin` to calculate radiance, as shown by the red lines in the following figure.
<img width="929" alt="屏幕截图 2024-05-12 161312" src="https://github.com/Twinklebear/webgpu-0-to-gltf/assets/139488963/6dc96131-3662-4672-bd58-153b96e1015a">
And the rendering result is right!
![屏幕截图 2024-05-12 161358](https://github.com/Twinklebear/webgpu-0-to-gltf/assets/139488963/f7e6f227-9573-464e-8665-0a21b536c48d)
But if I don't use `rgb2lin` as shown in the orange lines code below, the rendering result will be incorrect and overall brighter!
<img width="917" alt="屏幕截图 2024-05-12 161418" src="https://github.com/Twinklebear/webgpu-0-to-gltf/assets/139488963/8ed89bfc-a2f1-4726-a657-ddd26a73294b">
![屏幕截图 2024-05-12 161507](https://github.com/Twinklebear/webgpu-0-to-gltf/assets/139488963/79844cb4-a9f0-4eac-b6f4-12d95dab2585)

**Comment by yanglebupt** [comment]
And I also try to change the texture format between "bgra8unorm-srgb" and "bgra8unorm", no impact on rendering results！

**Comment by Twinklebear** [comment]
Interesting, it should be right with either using `rgb2lin` in the shader and not specifying the color space for the texture (ie using `bgra8unorm`, or not using `rgb2lin` and setting the texture to be `bgra8unorm-srgb` (these two configurations should produce the same image). It looks like you're scaling not just the emissive color value but also the strength factor when you're applying the `rgb2lin` to the emission value. That might be weighting the emission down so it looks less strong.

A good sanity check would be to compare these two options without any lighting or material shading, just use the color values from the textures.

**Comment by yanglebupt** [comment]
Ok, I figure out. Thank!
